# hr-ai-platform/docker-compose.yml
services:
  psql:
    container_name: psql
    image: hr-platform/hr-psql-service
    build: apps/hr-psql-service
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5433:5432"
    volumes:
      - ./data/psql:/var/lib/postgresql/data

  backend:
    container_name: backend
    image: hr-platform/hr-backend-service
    build: apps/hr-backend-service
    environment:
      DATABASE_URL: postgresql://jobmatch_user:secure_password@hr-psql-service:5432/jobmatch_ai
      NLP_SERVICE_URL: http://nlp:8001
    volumes:
      - ./data/uploads:/app/uploads

  nlp:
    container_name: nlp
    image: hr-platform/hr-nlp-service
    build: apps/hr-nlp-service

  nginx:
    container_name: nginx
    image: hr-platform/hr-nginx-service
    build: apps/hr-nginx-service
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./conf:/etc/nginx/templates/

  web:
    container_name: web
    image: hr-platform/hr-web-service
    build: apps/hr-web-service