# hr-ai-platform/docker-compose.yml
services:
  psql:
    image: hr-platform/hr-psql-service
    environment:
      POSTGRES_DB: jobmatch_ai
      POSTGRES_USER: jobmatch_user
      POSTGRES_PASSWORD: secure_password
    ports:
      - "5432:5432"
    volumes:
      - ./data/psql:/var/lib/postgresql/data

  backend:
    image: hr-platform/hr-backend-service
    build: apps/hr-backend-service
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://jobmatch_user:secure_password@hr-psql-service:5432/jobmatch_ai
      NLP_SERVICE_URL: http://nlp-service:8001
    depends_on:
      - db
      - nlp
    volumes:
      - ./data/uploads:/app/uploads

  nlp:
    image: hr-platform/hr-nlp-service
    build: apps/hr-nlp-service
    ports:
      - "8001:8001"