# hr-ai-platform/docker-compose.yml
services:
  api:
    container_name: api
    image: hr-platform/hr-api-gateway
    build: ../gateways/hr-api-gateway
    env_file: ../.env
    mem_limit: 2g
    cpus: 2